function generateConformalGoldenVectors()
% GENERATECONFORMALGOLDENVECTORS  Build tests/conformal_golden_vectors.json,
% for conformal policy v3 (score v3, referable-stratified Mondrian,
% referable-threshold safety gate), method
% 'ordinal_mode_interval_stratified_v3'.
%
%   Run: matlab -batch "generateConformalGoldenVectors"
%
%   Expected outputs (tier, predictionSet, low, high, contiguous, mode,
%   pReferable) are generated by THIS repo's MATLAB conformalTiering.m
%   against the deployed models/calibration_branchA_v2a.json (v2a, not v1 --
%   v2a is the model behind the switch this policy round is for). testConf
%   ormalV2.m and test_conformal_v2.py both reproduce every case here
%   exactly -- that reproduction, not this generator, is what verifies the
%   Python and MATLAB scoring/tiering code have not drifted apart. Re-run
%   this only when calibration_branchA_v2a.json is re-fitted.
%
%   Cases (>=80 total):
%     - ~65 REAL branchA_v2a pooled val+test probability rows (a fixed,
%       seeded sample -- real model output, not synthetic), pooled the same
%       way calibrateBranchA.m pools them for fitting.
%     - Edge cases: uniform, one-hot at every grade (0 and 4 explicitly
%       requested), exact ties incl. "mode at both ends"
%       ([0.5 0 0 0 0.5] -- the two extremes tied, mode resolves to the
%       HIGHER grade per the tie-break rule), the bimodal vector
%       [0.45 0 0 0.05 0.5] explicitly called out, cases as close as
%       mathematically possible to the referable-threshold boundary (see
%       the NOTE below on why an exact straddle is not reachable with the
%       real fitted numbers), and a hand-picked case where the per-stratum
%       thresholds reopen a gap that the contiguous hull then fills.
%
%   ── NOTE ON "STRADDLING referableThreshold": A STRUCTURAL FINDING ─────────
%   The referable-threshold demotion (conformalTiering.m) only ever applies
%   when the BASE algorithm already put the case in Tier A, which requires
%   s(2) = p0+p1 > qhatPerStratum(referable) for the case's own mode in
%   {0,1}. Since qhatPerStratum(referable) is fitted at ~0.87-0.88 (both v1
%   and v2a), Tier-A eligibility forces pReferable = 1-(p0+p1) < ~0.12-0.13
%   -- comfortably BELOW referableThreshold (~0.23-0.32 for the two fitted
%   models). Checked empirically too: 0/531 v2a Tier-A cases (pooled val+
%   test) ever reach the demotion condition. So with the ACTUAL deployed
%   numbers, no real probability vector can be both Tier-A-eligible and
%   above referableThreshold -- the gate is correctly implemented and does
%   real work as "defense in depth" against a future re-fit where the two
%   thresholds land differently, but is a structural no-op against TODAY's
%   fitted values. The golden vectors below include the closest-reachable
%   near-boundary case for regression coverage; the DEMOTION LOGIC ITSELF is
%   separately unit-tested in testConformalV2.m/test_conformal_v2.py against
%   a hand-built synthetic calibration where it IS reachable, since no real
%   calibration_branchA_v2a.json case can exercise it.

thisDir = fileparts(mfilename('fullpath'));
mlRoot  = fullfile(thisDir, '..');
addpath(fullfile(mlRoot, 'calibration'));

calibPath = fullfile(mlRoot, 'models', 'calibration_branchA_v2a.json');
calib = jsondecode(fileread(calibPath));
if ~strcmp(calib.method, 'ordinal_mode_interval_stratified_v3')
    error('generateConformalGoldenVectors:wrongMethod', ...
          'models/calibration_branchA_v2a.json is not fitted with the expected method.');
end

% Pool val+test the same way calibrateBranchA.m does for fitting -- these
% are the SAME probability rows the calibration was fitted from, used here
% only as a source of REALISTIC probability vectors for golden cases, not
% re-fitted on.
valLogits  = readmatrix(fullfile(mlRoot, 'models', 'Model1', 'v2a', 'val_logits.csv'));
testLogits = readmatrix(fullfile(mlRoot, 'models', 'Model1', 'v2a', 'test_logits.csv'));
poolLogits = [valLogits; testLogits];
T = calib.temperature;
poolProbs = softmaxRows(poolLogits / T);

rng(42);
nReal = 65;
idx = sort(randperm(size(poolProbs, 1), nReal));

cases = {};
for i = 1:numel(idx)
    p = poolProbs(idx(i), :);
    cases{end+1} = makeCase(sprintf('v2a_pool_row_%d', idx(i)), p, calib); %#ok<AGROW>
end

% ── Explicit edge cases (task-required + carried over from v2 for regression
%    coverage) ──────────────────────────────────────────────────────────────
edge = struct( ...
    'uniform',                [0.2 0.2 0.2 0.2 0.2], ...
    'onehot_grade0',           [1 0 0 0 0], ...
    'onehot_grade1',           [0 1 0 0 0], ...
    'onehot_grade2',           [0 0 1 0 0], ...
    'onehot_grade3',           [0 0 0 1 0], ...
    'onehot_grade4',           [0 0 0 0 1], ...
    'bimodal_mode_grade4',     [0.45 0 0 0.05 0.5], ...
    'mode_at_both_ends_tie',   [0.5 0 0 0 0.5], ...
    'tie_grade0_grade1',       [0.5 0.5 0 0 0], ...
    'tie_grade3_grade4',       [0 0 0 0.5 0.5], ...
    'tie_grade1_grade2',       [0 0.5 0.5 0 0], ...
    'three_way_tie_024',       [1/3 0 1/3 0 1/3], ...
    'peaked_grade4',           [0.02 0.02 0.02 0.02 0.92], ...
    'peaked_grade0',           [0.92 0.02 0.02 0.02 0.02], ...
    'near_boundary_low',       [0.55 0.45 0 0 0], ...
    'near_boundary_high',      [0 0 0.45 0.55 0], ...
    'flat_referable_side',     [0 0 0.25 0.25 0.5], ...
    'flat_nonreferable_side',  [0.5 0.25 0.25 0 0], ...
    'spike_grade2',            [0.05 0.05 0.8 0.05 0.05], ...
    ... % Closest mathematically-reachable approach to the referable-
    ... % threshold boundary from Tier-A-eligible territory (see the NOTE
    ... % above): mode=0, s(2)=p0+p1 just over qhatPerStratum(referable), so
    ... % pReferable sits just under (1 - qhatPerStratum(referable)), the
    ... % largest pReferable a Tier-A-eligible v2a case can have.
    'near_referable_threshold_from_tierA', [0.85 0.03 0.06 0.04 0.02] ...
    );

fields = fieldnames(edge);
for i = 1:numel(fields)
    cases{end+1} = makeCase(fields{i}, edge.(fields{i}), calib); %#ok<AGROW>
end

% ── Hand-picked hull-fills-gap case: search the real pool for a row whose
%    RAW (pre-hull) membership is non-contiguous, so the golden set includes
%    at least one real example of the hull actually doing work ──────────────
gapCaseAdded = false;
for i = 1:size(poolProbs, 1)
    [tier, d] = conformalTiering(poolProbs(i, :), calib); %#ok<ASGLU>
    if ~d.contiguous
        cases{end+1} = makeCase(sprintf('v2a_pool_row_%d_gap_filled', i), poolProbs(i, :), calib); %#ok<AGROW>
        gapCaseAdded = true;
        break;
    end
end
if ~gapCaseAdded
    fprintf(['NOTE: no non-contiguous raw-membership case found in the v2a pool -- ' ...
             'omitting the hull-fills-gap case (nothing to fill).\n']);
end

fprintf('generated %d golden cases\n', numel(cases));

out = struct( ...
    'method',         calib.method, ...
    'calibrationFile', 'models/calibration_branchA_v2a.json', ...
    'generatedBy',    'generateConformalGoldenVectors.m', ...
    'note',           ['Uses branchA_v2a''s calibration (the model behind the switch this ' ...
                       'policy round is for), not v1''s. See this file''s own header for why ' ...
                       'a true referable-threshold-straddle case is not reachable with the ' ...
                       'real fitted numbers, and where that logic is separately unit-tested.'], ...
    'cases',          {cases});

outPath = fullfile(thisDir, 'conformal_golden_vectors.json');
fid = fopen(outPath, 'w');
if fid == -1, error('generateConformalGoldenVectors:writeFailed', 'could not write %s', outPath); end
fprintf(fid, '%s', jsonencode(out, 'PrettyPrint', true));
fclose(fid);
fprintf('wrote %s\n', outPath);
end

function c = makeCase(id, probs, calib)
% NOTE: fields are built with dot-assignment, not struct(...) positional
% args -- struct() expands a CELL positional argument into a struct ARRAY
% (comma-separated-list expansion), which silently produced one JSON object
% per set element instead of one case with an array field the first time
% this was written. Dot-assignment stores a cell as a plain field value, and
% jsonencode always serializes a cell array as a JSON array (even length 1),
% which a plain 1x1 double row would NOT (it serializes as a bare number).
probs = double(probs(:))';
probs = probs / sum(probs);
[tier, details] = conformalTiering(probs, calib);

expected = struct();
expected.tier = tier;
expected.predictionSet = num2cell(details.predictionSet);
expected.low = details.low;
expected.high = details.high;
expected.setSize = details.setSize;
expected.contiguous = details.contiguous;
expected.mode = details.mode;
expected.pReferable = details.pReferable;

c = struct();
c.id = id;
c.probs = probs;
c.expected = expected;
end

function p = softmaxRows(s)
s = s - max(s, [], 2);
e = exp(s);
p = e ./ sum(e, 2);
end
