-- =============================================================================
-- Central system PostgreSQL schema
-- Database: dr_screening_central
-- Run via:  node scripts/setupCentralDb.js            (create / update)
--           node scripts/setupCentralDb.js --reset    (DROP everything first)
--
-- AUTHORITY
--   This file implements Task 0.3 of docs/implementation-plan-backend-ml.md,
--   reconciled against docs/api-contracts.md. Per api-contracts.md's own rule,
--   where the plan and the contract disagree, THE CONTRACT WINS and the plan is
--   treated as out of date. Every such case is commented inline with a
--   "CONTRACT:" note, so the divergence is auditable rather than silent.
--
-- NAMING
--   Columns are snake_case. Every HTTP payload is camelCase. The conversion
--   happens in the route handler only -- never in the DB layer, never in a
--   frontend component (api-contracts.md, "Global naming rule").
--
-- IDs
--   patients.patient_id and cases.capture_id_ref are TEXT, not UUID: they are
--   generated by the PHC local app as {PHC_CODE}-{base36 ts}-{4 rand}, e.g.
--   'PHC001-lz3k9f-a2x9' (api-contracts.md, "Global ID rule"). Centrally
--   generated IDs (case_id, review_id, referral_id, ...) are UUIDv4.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- 1. phc_sites -- one row per Primary Health Centre
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS phc_sites (
  phc_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,

  -- CONTRACT: GET /api/v1/phc/:phcId/sync-status returns lastSyncAt and
  -- pendingCount. Task 0.3's DDL has neither, so both are additive.
  --
  -- pending_count is REPORTED BY the PHC on each sync, not computed here: the
  -- sync queue lives in that PHC's local SQLite and this server cannot see it.
  -- So the value is only true as of last_sync_at, and the PHC whose backlog is
  -- actually growing is precisely the offline one whose number is frozen. The
  -- two columns are meaningless apart and must always be read together.
  last_sync_at  TIMESTAMPTZ,
  pending_count INTEGER NOT NULL DEFAULT 0
);

-- -----------------------------------------------------------------------------
-- 2. model_versions -- declared before grading_results, which references it
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS model_versions (
  version_id              TEXT PRIMARY KEY,   -- e.g. 'branchA_v1'
  trained_at              TIMESTAMPTZ,
  validation_sensitivity  REAL,
  validation_specificity  REAL,
  validation_kappa        REAL,
  promoted                BOOLEAN NOT NULL DEFAULT false,
  promoted_at             TIMESTAMPTZ
);

-- -----------------------------------------------------------------------------
-- 3. patients -- mirrors the PHC local app's patient records after sync
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS patients (
  patient_id        TEXT PRIMARY KEY,   -- PHC-generated, e.g. 'PHC001-lz3k9f-a2x9'
  name              TEXT NOT NULL,
  age               INTEGER NOT NULL,
  contact_number    TEXT NOT NULL,      -- required: only channel for delayed results
  registered_at     TIMESTAMPTZ NOT NULL,

  -- CONTRACT: the ophthalmologist queue and case detail return patientReference
  -- ("PT-4821"), explicitly "a display-safe identifier, never the raw patientId".
  -- Storing it keeps that guarantee enforceable in one place, instead of relying
  -- on every route handler to remember to mask the real ID.
  patient_reference TEXT UNIQUE
);

-- -----------------------------------------------------------------------------
-- 4. cases -- one screening submission (image + both questionnaires)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cases (
  case_id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id             TEXT NOT NULL REFERENCES patients(patient_id),
  phc_id                 UUID REFERENCES phc_sites(phc_id),
  capture_id_ref         TEXT,          -- traceability to the local capture_id
  camera_device_id       TEXT,          -- worker-reported (capture-metadata form)
  camera_family_detected TEXT,          -- image-derived (Task 6.3); NULL until then
  image_path             TEXT NOT NULL,
  questionnaire_data     JSONB,         -- patient symptom/risk answers
  capture_metadata       JSONB,         -- capture-context answers
  received_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- CONTRACT: the ophthalmologist queue and case detail return capturedAt.
  -- This is NOT received_at. The system is offline-first by design: a capture
  -- may sit in the PHC's sync queue for days before it reaches this server
  -- (design doc §1.4, §8.2), so received_at can be far later than the moment
  -- the patient was actually photographed. An ophthalmologist triaging a case
  -- needs the capture date -- it is the clinical fact -- and using received_at
  -- as a stand-in would silently misreport every case that synced late, which
  -- is precisely the rural deployment this system is built for.
  captured_at            TIMESTAMPTZ,

  -- CONTRACT: GET /api/v1/cases/:caseId/status returns exactly
  -- "processing" | "graded" | "error". Task 0.3's DDL omits this column
  -- entirely, so that endpoint cannot be built without it.
  status                 TEXT NOT NULL DEFAULT 'processing'
                         CHECK (status IN ('processing','graded','error'))
);

-- -----------------------------------------------------------------------------
-- 5. grading_results -- dual-branch grading + calibration output
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS grading_results (
  result_id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id               UUID NOT NULL REFERENCES cases(case_id) ON DELETE CASCADE,

  -- Phase 2 (Task 2.7) -- populated now
  dr_grade_cnn          INTEGER CHECK (dr_grade_cnn BETWEEN 0 AND 4),
  referable             BOOLEAN,        -- dr_grade_cnn >= 2
  confidence_score      REAL,           -- POST-calibration: max(applyTemperature(...))
  conformal_tier        TEXT CHECK (conformal_tier IN ('A','B','C')),
  model_version         TEXT REFERENCES model_versions(version_id),
  graded_at             TIMESTAMPTZ,

  -- Phase 5 (Tasks 5.1/5.2) -- NULL until the rule engine ships
  dr_grade_rule_engine  INTEGER CHECK (dr_grade_rule_engine BETWEEN 0 AND 4),
  branch_agreement      BOOLEAN,

  -- Phase 6 (Task 6.1) -- NULL until MC-Dropout ships
  uncertainty_score     REAL,

  -- One grading result per case. gradingOrchestrator.js depends on this
  -- constraint for its INSERT ... ON CONFLICT (case_id) DO UPDATE re-grade path.
  UNIQUE (case_id)
);

-- -----------------------------------------------------------------------------
-- 6. segmentation_outputs -- Phase 4 output (all NULL until then)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS segmentation_outputs (
  case_id            UUID PRIMARY KEY REFERENCES cases(case_id) ON DELETE CASCADE,
  lesion_masks_path  TEXT,
  lesion_counts      JSONB,  -- {"microaneurysms":6,...}, quadrant-mapped; feeds Branch B
  nv_suspicion_score REAL,   -- suspicion signal, NOT a validated detector (design §1.12)
  vessel_map_path    TEXT,
  optic_disc_x       REAL,
  optic_disc_y       REAL,
  fovea_x            REAL,
  fovea_y            REAL
);

-- -----------------------------------------------------------------------------
-- 7. explainability_outputs -- Grad-CAM and its safeguards
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS explainability_outputs (
  case_id                            UUID PRIMARY KEY REFERENCES cases(case_id) ON DELETE CASCADE,

  -- Phase 2 (Task 2.7) -- populated now
  gradcam_path                       TEXT,

  -- Phase 7 (Task 7.1) -- NULL until the safeguards ship
  lesion_attention_consistency_score REAL,
  evidence_summary_text              TEXT
);


-- -----------------------------------------------------------------------------
-- 8. ophthalmologist_reviews -- confirm/override audit trail
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ophthalmologist_reviews (
  review_id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id                  UUID NOT NULL REFERENCES cases(case_id) ON DELETE CASCADE,
  ophthalmologist_id       TEXT,
  decision                 TEXT NOT NULL CHECK (decision IN ('confirm','override')),
  override_reason_category TEXT CHECK (override_reason_category IN
                             ('artifact_misread','lesion_missed',
                              'wrong_severity','image_quality_issue')),
  override_reason_text     TEXT,
  review_duration_seconds  INTEGER,
  reviewed_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- CONTRACT: overrideReasonCategory is null when decision is 'confirm', and one
  -- of the four enum values otherwise. Enforced here so a route bug cannot
  -- record an override with no reason attached.
  CONSTRAINT override_requires_category CHECK (
    (decision = 'confirm'  AND override_reason_category IS NULL) OR
    (decision = 'override' AND override_reason_category IS NOT NULL)
  )
);

-- -----------------------------------------------------------------------------
-- 9. referrals -- loss-to-follow-up tracking
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS referrals (
  referral_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id         UUID NOT NULL REFERENCES cases(case_id) ON DELETE CASCADE,
  -- CONTRACT: status enum is referred -> contacted -> attended | lost.
  status          TEXT NOT NULL DEFAULT 'referred'
                  CHECK (status IN ('referred','contacted','attended','lost')),
  assigned_worker TEXT,                 -- ASHA / community health worker
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 10. notifications -- outbound SMS log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
  notification_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id      TEXT REFERENCES patients(patient_id),
  case_id         UUID REFERENCES cases(case_id) ON DELETE CASCADE,
  channel         TEXT,   -- 'sms'
  message_type    TEXT,   -- 'positive' | 'negative'
  sent_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 11. corrections -- links an override to the retraining run that consumed it
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS corrections (
  correction_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id               UUID REFERENCES cases(case_id) ON DELETE CASCADE,
  review_id             UUID REFERENCES ophthalmologist_reviews(review_id) ON DELETE CASCADE,
  used_in_model_version TEXT REFERENCES model_versions(version_id)
);

-- -----------------------------------------------------------------------------
-- 12. users -- role-based access for the central website (design doc §5.1)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  user_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email         TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('ophthalmologist','district_admin')),
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- Additive migrations
--
-- CREATE TABLE IF NOT EXISTS silently SKIPS a table that already exists, so a
-- column added to a definition above never reaches a database that was created
-- before it. These ALTERs are how an existing dev database picks those changes
-- up without a destructive --reset. They are no-ops on a fresh install, where
-- the column is already present from the CREATE above.
--
-- Keep every entry here idempotent (IF NOT EXISTS), and add to this list rather
-- than editing a CREATE alone, or the two paths drift apart.
-- -----------------------------------------------------------------------------
ALTER TABLE cases     ADD COLUMN IF NOT EXISTS captured_at   TIMESTAMPTZ;
-- The PHC quality gate's six sub-scores, forwarded by the sync manager. They
-- steer Task 2.8's adaptive enhancement, which needs to know WHICH dimension of
-- an image is weak in order to correct that one rather than applying a fixed
-- chain to everything. Nullable: captures taken before this existed have none,
-- and the pipeline falls back to the default chain for those.
ALTER TABLE cases     ADD COLUMN IF NOT EXISTS quality_scores JSONB;
ALTER TABLE phc_sites ADD COLUMN IF NOT EXISTS pending_count INTEGER NOT NULL DEFAULT 0;

-- notifications: a row must record what ACTUALLY happened, not merely that a
-- send was attempted. Without a status, a row inserted when Twilio is not
-- configured -- or when the send failed -- is indistinguishable from a
-- delivered message, and the system would report having told a patient to seek
-- care when it never did. For a referral pathway that is the worst possible
-- kind of wrong record.
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS status              TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS provider_message_id TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS error_detail        TEXT;

-- One referral per case. A case can be reviewed more than once (a confirm
-- followed later by an override, say), and without this a second review would
-- create a second referral and send the patient a second SMS about the same
-- screening. Enforced in the database rather than only in code, because the
-- cost of getting it wrong is a real message to a real patient.
CREATE UNIQUE INDEX IF NOT EXISTS uq_referrals_case ON referrals(case_id);

-- -----------------------------------------------------------------------------
-- Indexes for the query patterns api-contracts.md's endpoints actually use
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_cases_patient     ON cases(patient_id);
CREATE INDEX IF NOT EXISTS idx_cases_status      ON cases(status);
CREATE INDEX IF NOT EXISTS idx_cases_phc         ON cases(phc_id);
CREATE INDEX IF NOT EXISTS idx_cases_received_at ON cases(received_at);  -- casesToday
CREATE INDEX IF NOT EXISTS idx_grading_case      ON grading_results(case_id);
CREATE INDEX IF NOT EXISTS idx_grading_tier      ON grading_results(conformal_tier);
CREATE INDEX IF NOT EXISTS idx_reviews_case      ON ophthalmologist_reviews(case_id);
CREATE INDEX IF NOT EXISTS idx_referrals_status  ON referrals(status);
