function result = calculateUrgencyScore(drGrade, patientAge, yearsDiabetic, bloodSugarHbA1c)
% CALCULATEURGENCYSCORE  Triage urgency (1-100) from the DR grade plus the
% patient's clinical history, using a Random Forest (Statistics and Machine
% Learning Toolbox: TreeBagger).
%
%   result = calculateUrgencyScore(drGrade, patientAge, yearsDiabetic, hba1c)
%   calculateUrgencyScore('selftest')      run the checks at the bottom
%
%   Inputs
%     drGrade          0-4, from Branch A / Branch B
%     patientAge       years, 1-120
%     yearsDiabetic    years since diagnosis, 0-80
%     bloodSugarHbA1c  HbA1c %, 4.0-20.0
%
%   Output: a struct with
%     urgencyScore     integer 1-100
%     topRiskFactor    the input that contributed most FOR THIS PATIENT
%     factors          every input with its contribution, descending
%     model            what produced the number (see the warning below)
%     limitation       the sentence that must travel with the score
%
%   ═══════════════════════════════════════════════════════════════════════
%   READ THIS BEFORE SHOWING THE NUMBER TO ANYONE
%
%   THIS MODEL IS TRAINED ON SYNTHETIC DATA. There is no clinical dataset of
%   triage urgency behind it. makeTrainingData() below writes 500 rows from a
%   formula THIS FILE INVENTS, and the forest then learns that formula back.
%
%   So the score is a re-expression of an assumption, dressed in the
%   vocabulary of a trained model. It is NOT evidence about a patient, it has
%   never been validated against an outcome, and a forest fitted to a rule
%   cannot know more than the rule.
%
%   That is legitimate as a prioritisation aid -- it orders a queue in a way
%   that is explicit and inspectable, which beats an unwritten instinct -- and
%   it is NOT legitimate as a clinical claim. Every surface that shows this
%   number must show `limitation` with it. The field exists so that nothing
%   downstream can display the score while quietly dropping the caveat.
%
%   What would make it real: urgency labels from ophthalmologists on actual
%   cases (how soon did this patient need to be seen?), then refit on those
%   and report held-out error. Until then the honest description is
%   "a transparent weighting, computed by a forest".
%   ═══════════════════════════════════════════════════════════════════════
%
%   Deterministic by construction: the training seed is fixed, so the same
%   patient always gets the same score. A triage number that moved between
%   runs could not be defended to the patient it reordered.

if nargin == 1 && (ischar(drGrade) || isstring(drGrade)) ...
        && strcmpi(string(drGrade), "selftest")
    result = selftest();
    return;
end

narginchk(4, 4);
x = validateInputs(drGrade, patientAge, yearsDiabetic, bloodSugarHbA1c);

mdl = urgencyModel();

score = predictScore(mdl, x);
factors = attribute(mdl, x, score);

result = struct( ...
    'urgencyScore',  score, ...
    'topRiskFactor', factors(1).label, ...
    'factors',       factors, ...
    'model', struct( ...
        'type',            'TreeBagger regression (Statistics and Machine Learning Toolbox)', ...
        'trees',           mdl.NumTrees, ...
        'trainingRows',    mdl.NumObservations, ...
        'trainingData',    'SYNTHETIC -- generated by makeTrainingData() in this file', ...
        'oobRmse',         mdl.oobRmse, ...
        'validatedAgainstOutcomes', false), ...
    'limitation', ['Trained on synthetic data generated from an assumed ' ...
                   'formula, not on clinical outcomes. Use to order a ' ...
                   'queue, never as evidence about a patient.']);
end

% ═══════════════════════════════════════════════════════════════════════════
function x = validateInputs(drGrade, patientAge, yearsDiabetic, hba1c)
% Every input is required and must be real. NOTHING is imputed here.
%
% The tempting alternative -- fill a missing HbA1c with the population median
% and carry on -- produces a confident-looking number for a patient nobody
% measured, and no field in the output would say so. A caller that lacks a
% value must decide what to do about it in the open; see the wiring notes at
% the bottom of this file.
    function v = num(val, name, lo, hi)
        if ~isnumeric(val) || ~isscalar(val) || ~isfinite(val)
            error('calculateUrgencyScore:badInput', ...
                '%s must be a finite numeric scalar; got %s.', name, class(val));
        end
        v = double(val);
        if v < lo || v > hi
            error('calculateUrgencyScore:outOfRange', ...
                '%s = %g is outside the plausible range [%g, %g].', name, v, lo, hi);
        end
    end

g = num(drGrade, 'drGrade', 0, 4);
if mod(g, 1) ~= 0
    error('calculateUrgencyScore:badInput', 'drGrade must be an integer 0-4.');
end

x = [g, ...
     num(patientAge,    'patientAge',      1, 120), ...
     num(yearsDiabetic, 'yearsDiabetic',   0,  80), ...
     num(hba1c,         'bloodSugarHbA1c', 4,  20)];

% A patient cannot have been diabetic for longer than they have been alive.
% Caught here rather than scored: the forest would happily extrapolate and
% return a plausible number for an impossible patient, which is how a data
% entry error becomes a clinical priority.
if x(3) > x(2)
    error('calculateUrgencyScore:impossiblePatient', ...
        'yearsDiabetic (%g) exceeds patientAge (%g).', x(3), x(2));
end
end

% ═══════════════════════════════════════════════════════════════════════════
function mdl = urgencyModel()
% The trained forest, cached for the life of the MATLAB session.
%
% PERSISTENT, not retrained per call: the brief says "train instantly", and it
% is roughly a quarter of a second -- but the backend grades cases in a
% long-lived MATLAB session, so per-call training would pay that on every
% patient forever to rebuild an identical model. Identical because the seed is
% fixed; without the seed the same patient would score differently between
% calls, which is the part that actually matters.
persistent CACHE
if ~isempty(CACHE)
    mdl = CACHE;
    return;
end

SEED = 20260921;
NTREES = 100;

% rng state is saved and restored: this function must not reach out and change
% the random stream of whatever called it. A caller drawing MC-dropout samples
% next would silently get a reseeded stream.
state = rng;
cleanup = onCleanup(@() rng(state));
rng(SEED, 'twister');

[X, y] = makeTrainingData(500);

% A regression forest, not a classifier: urgency is a position on a scale, and
% a 5-class or 10-bucket classifier would throw away the ordering (a case
% scored 61 is nearer 60 than 20, and a classifier is free to disagree).
bag = TreeBagger(NTREES, X, y, ...
    'Method', 'regression', ...
    'OOBPrediction', 'on', ...
    'MinLeafSize', 5);

% Out-of-bag error, reported in the output so the number carries its own
% accuracy. On synthetic data this measures how well the forest learned the
% formula -- NOT how well it predicts urgency in a clinic.
oobPred = oobPredict(bag);
mdl = struct('bag', bag, 'NumTrees', NTREES, 'NumObservations', size(X, 1), ...
             'oobRmse', sqrt(mean((oobPred - y).^2)), ...
             'featureNames', {{'drGrade', 'patientAge', 'yearsDiabetic', 'bloodSugarHbA1c'}});
CACHE = mdl;
end

% ═══════════════════════════════════════════════════════════════════════════
function [X, y] = makeTrainingData(n)
% 500 synthetic patients and the urgency this file ASSUMES they warrant.
%
% ── WHERE THE SHAPE COMES FROM ─────────────────────────────────────────────
% The weights below are clinical common sense, not fitted values:
%
%   drGrade dominates.        It is the only input that is a direct
%                             observation of the eye. Grade 4 (proliferative)
%                             is an ophthalmic emergency; grade 0 is not.
%                             Its contribution is deliberately non-linear --
%                             the step from 3 to 4 is worth more than 0 to 1.
%   HbA1c matters mostly      Poor control predicts PROGRESSION, so it raises
%   when there is disease.    urgency far more for a grade 2 than a grade 0.
%                             That is the interaction term, and it is the one
%                             thing here a linear model could not express --
%                             which is the honest reason to use a forest.
%   Duration adds slowly      Risk accumulates with years of exposure, with
%   and saturates.            diminishing effect after ~20 years.
%   Age contributes least.    It is a weak modifier, included because the
%                             brief asks for it, and the attribution below
%                             will correctly report it as rarely the top
%                             factor.
%
% Noise is added so the forest fits a cloud rather than memorising an exact
% surface -- without it, OOB error would be near zero and would look like
% evidence of accuracy rather than evidence of a formula being learned back.

drGrade   = randi([0 4], n, 1);
patientAge = round(30 + 45 * rand(n, 1));               % 30-75
yearsDiabetic = min(round(exprnd(8, n, 1)), patientAge - 18);
yearsDiabetic = max(yearsDiabetic, 0);
hba1c     = 5.5 + 5.5 * betarnd(2, 3, n, 1);            % ~5.5-11, skewed low

gradeTerm = 12 * drGrade + 3 * drGrade.^2;              % 0, 15, 36, 63, 96
hba1cTerm = 2.2 * max(0, hba1c - 6.5);                  % nothing below target
interact  = 1.6 * max(0, hba1c - 6.5) .* drGrade;       % poor control WITH disease
durTerm   = 9 * (1 - exp(-yearsDiabetic / 10));         % saturating
ageTerm   = 0.08 * max(0, patientAge - 40);

y = 5 + gradeTerm + hba1cTerm + interact + durTerm + ageTerm + 4 * randn(n, 1);
y = min(100, max(1, y));

X = [drGrade, patientAge, yearsDiabetic, hba1c];
end

% ═══════════════════════════════════════════════════════════════════════════
function score = predictScore(mdl, x)
score = predict(mdl.bag, x);
score = round(min(100, max(1, score)));
end

% ═══════════════════════════════════════════════════════════════════════════
function factors = attribute(mdl, x, score)
% Which input drove THIS patient's score, by exact Shapley value.
%
% NOT OOBPermutedPredictorDeltaError: that is a global ranking -- "which
% feature matters across all patients" -- so it would name the same factor on
% every row, usually drGrade, which tells a nurse nothing.
%
% And not the obvious one-at-a-time counterfactual either, which is what this
% function did first and got WRONG. Move one input to baseline, measure the
% drop, repeat: the trouble is the interaction term. HbA1c only hurts when
% there is retinopathy, so removing the grade also removes the interaction,
% and removing the HbA1c removes it too -- both get credit for the same
% points. On a grade-1 patient with HbA1c 12 that scored the grade at +13 and
% the sugar at +12 when the truth is that the sugar is the actionable one, and
% the four contributions summed to 25 of the 28 points actually above
% baseline. A ranking decided by an accounting error is worse than no ranking.
%
% Shapley splits shared credit by averaging each feature's marginal effect
% over every order the features could be added in. With four features that is
% 16 coalitions -- 16 forest predictions, microseconds -- so the exact value
% is computable and there is no reason to approximate it. The contributions
% then SUM to the score above baseline, which is the property that makes them
% explainable to a clinician.
BASELINE = [0, 40, 0, 6.0];
LABELS = {'DR grade', 'Age', 'Years diabetic', 'HbA1c'};
DESCRIPTIONS = { ...
    @(v) sprintf('DR grade %d', v), ...
    @(v) sprintf('age %d', round(v)), ...
    @(v) sprintf('%d years diabetic', round(v)), ...
    @(v) sprintf('HbA1c %.1f%%', v)};

n = numel(LABELS);

% v(S): the score when the features in S take the patient's values and the
% rest sit at baseline. Every coalition is evaluated once, up front.
v = zeros(1, 2^n);
for mask = 0:(2^n - 1)
    z = BASELINE;
    for k = 1:n
        if bitget(mask, k), z(k) = x(k); end
    end
    % yearsDiabetic can exceed a baseline age of 40 -- an impossible patient
    % the forest would still score. Clamped so no coalition is evaluated
    % outside the space the training data covers.
    z(3) = min(z(3), z(2));
    v(mask + 1) = predictRaw(mdl, z);
end

% Shapley: for each feature, the weighted mean of its marginal contribution
% over all subsets that do not contain it.
contrib = zeros(1, n);
for k = 1:n
    for mask = 0:(2^n - 1)
        if bitget(mask, k), continue; end
        sz = sum(bitget(mask, 1:n));
        w = factorial(sz) * factorial(n - sz - 1) / factorial(n);
        contrib(k) = contrib(k) + w * (v(bitset(mask, k) + 1) - v(mask + 1));
    end
end

[~, order] = sort(contrib, 'descend');
factors = struct('label', {}, 'value', {}, 'contribution', {}, 'detail', {});
for i = 1:n
    k = order(i);
    factors(i) = struct( ...
        'label', LABELS{k}, ...
        'value', x(k), ...
        'contribution', round(contrib(k), 1), ...
        'detail', DESCRIPTIONS{k}(x(k))); %#ok<AGROW>
end

% Nothing meaningful above baseline is a real answer, and naming a "top risk
% factor" for a healthy patient would be a wrong one. The floor is 2 points
% rather than 0 because forest noise alone moves a contribution by about a
% point: a 30-year-old with no disease was being told their top risk factor
% was "Age", on +1.0, which is a rounding artefact presented as a finding.
if factors(1).contribution < 2
    factors(1).label = 'No elevated risk factor';
    factors(1).detail = 'every input is at or below its baseline';
end
end

% ═══════════════════════════════════════════════════════════════════════════
function raw = predictRaw(mdl, x)
% Unrounded and unclamped, for attribution only. Rounding inside the Shapley
% sum would quantise 16 predictions into the contributions and stop them
% adding up to the score.
raw = predict(mdl.bag, x);
end

% ═══════════════════════════════════════════════════════════════════════════
function ok = selftest()
% Properties that must hold whatever the forest fitted. These are not accuracy
% claims -- there is nothing to be accurate against -- they are checks that
% the thing behaves like a triage score rather than like noise.
fprintf('\n=== calculateUrgencyScore selftest ===\n');
pass = 0; fail = 0;
    function check(label, cond, detail)
        if cond
            fprintf('  PASS  %s\n', label); pass = pass + 1;
        else
            fprintf('  FAIL  %s\n', label); fail = fail + 1;
            if nargin > 2, fprintf('        %s\n', detail); end
        end
    end

% 1. Determinism. The same patient, twice, in the same session and across a
%    cache rebuild: a triage number that moves cannot be defended.
a = calculateUrgencyScore(2, 55, 10, 8.5);
b = calculateUrgencyScore(2, 55, 10, 8.5);
clear functions %#ok<CLFUNC>  % drop the persistent cache, retrain from the seed
c = calculateUrgencyScore(2, 55, 10, 8.5);
check('the same patient scores the same twice', a.urgencyScore == b.urgencyScore);
check('and the same again after the model is retrained', a.urgencyScore == c.urgencyScore, ...
    sprintf('%d vs %d', a.urgencyScore, c.urgencyScore));

% 2. Monotonic in the DR grade, holding everything else. If a worse eye can
%    score lower, the score is not a triage order.
scores = arrayfun(@(g) calculateUrgencyScore(g, 55, 10, 8.5).urgencyScore, 0:4);
check('a worse DR grade never scores lower', all(diff(scores) >= 0), mat2str(scores));
check('grade 4 outranks grade 0 by a wide margin', scores(5) - scores(1) >= 40, mat2str(scores));

% 3. Monotonic in HbA1c for a patient who already has disease.
h = arrayfun(@(v) calculateUrgencyScore(2, 55, 10, v).urgencyScore, [6 7 8 9 10]);
check('worse glycaemic control never scores lower', all(diff(h) >= 0), mat2str(h));

% 4. The interaction the forest exists for: HbA1c should matter MORE when
%    there is retinopathy than when there is none.
d0 = calculateUrgencyScore(0, 55, 10, 10).urgencyScore - calculateUrgencyScore(0, 55, 10, 6).urgencyScore;
d3 = calculateUrgencyScore(3, 55, 10, 10).urgencyScore - calculateUrgencyScore(3, 55, 10, 6).urgencyScore;
check('HbA1c weighs more with disease than without', d3 > d0, sprintf('grade0 +%d vs grade3 +%d', d0, d3));

% 5. Range.
lo = calculateUrgencyScore(0, 30, 0, 5.0).urgencyScore;
hi = calculateUrgencyScore(4, 75, 30, 12.0).urgencyScore;
check('a healthy young patient scores low', lo <= 25, num2str(lo));
check('the worst case scores high', hi >= 85, num2str(hi));
check('every score stays within 1-100', lo >= 1 && hi <= 100);

% 6. Attribution names something a nurse can act on, per patient.
sugar = calculateUrgencyScore(1, 50, 5, 12.0);
grade = calculateUrgencyScore(4, 50, 5, 6.0);
check('poor control on a mild eye blames HbA1c', ...
    strcmp(sugar.topRiskFactor, 'HbA1c'), sugar.topRiskFactor);
check('severe disease with good control blames the DR grade', ...
    strcmp(grade.topRiskFactor, 'DR grade'), grade.topRiskFactor);
check('a patient at baseline is not blamed for anything', ...
    strcmp(calculateUrgencyScore(0, 40, 0, 6.0).topRiskFactor, 'No elevated risk factor'));

% 7. Refusals. Nothing is imputed, nothing impossible is scored.
    function tf = throws(f)
        tf = false;
        try, f(); catch, tf = true; end
    end
check('a missing HbA1c is refused, not imputed', throws(@() calculateUrgencyScore(2, 55, 10, NaN)));
check('a grade of 7 is refused', throws(@() calculateUrgencyScore(7, 55, 10, 8.5)));
check('30 years diabetic at age 25 is refused', throws(@() calculateUrgencyScore(2, 25, 30, 8.5)));

% 8. The caveat cannot be lost by accident.
check('every result carries its limitation', ...
    ischar(a.limitation) && contains(a.limitation, 'synthetic'));
check('and says it was never validated against outcomes', ...
    a.model.validatedAgainstOutcomes == false);

fprintf('\n  OOB RMSE on the synthetic data: %.2f points (how well the forest\n', a.model.oobRmse);
fprintf('  learned the formula -- NOT how well it predicts real urgency)\n');
fprintf('\n===== %d passed, %d failed =====\n', pass, fail);
ok = (fail == 0);
end

% ═══════════════════════════════════════════════════════════════════════════
% WIRING IT INTO gradingOrchestrator.js
% ═══════════════════════════════════════════════════════════════════════════
%
% 1. THE DATA WE DO NOT HAVE. This is the blocker, and it is not a code
%    problem. The function takes yearsDiabetic as an integer and HbA1c as a
%    float. The PHC questionnaire collects neither. What cases.questionnaire_data
%    actually holds today is:
%
%      riskFactors.glycemicControl    'good' | 'moderate' | 'poor'
%      riskFactors.yearsSinceDiagnosis 'lt1' | ... (buckets)
%      riskFactors.bloodPressure      'normal' | 'high'
%
%    and patientAge comes from patients.age, which IS a real number.
%
%    So there are two honest routes, and they should not be mixed:
%
%      (a) Collect the real values. Add an HbA1c field and a years field to
%          the capture questionnaire. The score then has real inputs.
%      (b) Map the buckets to representative numbers (e.g. poor -> 9.5%,
%          moderate -> 7.5%, good -> 6.2%) and record in the output that the
%          inputs were ASSUMED. A score built on a bucket midpoint is much
%          coarser than one built on a lab value, and the case detail must
%          say which it was.
%
%    What must NOT happen: mapping buckets silently, so a screen shows
%    "HbA1c 9.5%" for a patient who never had the test.
%
% 2. WHERE IT RUNS. Inside the existing per-case MATLAB call, not as a new
%    spawn. runCasePipeline.m already receives the case's inputs and returns
%    one struct; add the fields there:
%
%      if isfield(in, 'clinical') && ~isempty(in.clinical)
%          u = calculateUrgencyScore(gradeForUrgency, in.clinical.patientAge, ...
%                                    in.clinical.yearsDiabetic, in.clinical.hba1c);
%          out.urgencyScore  = u.urgencyScore;
%          out.topRiskFactor = u.topRiskFactor;
%          out.urgencyLimitation = u.limitation;
%      end
%
%    The forest is cached per session, so only the first case pays the ~0.25 s
%    of training.
%
% 3. WHICH GRADE GOES IN. Use the grade the system stands behind: Branch A's
%    CNN grade, EXCEPT where the reviewer has already corrected it, in which
%    case the corrected grade wins. Feeding an unreviewed grade into a triage
%    score is the same trust decision the tiering already makes -- so if the
%    case is Tier C (mandatory review), the urgency score is a queue hint,
%    not a clinical instruction, and should be labelled as such.
%
% 4. WHAT THE BACKEND DOES WITH IT. buildCasePipelineInput() gains a
%    `clinical` block, assembled in Node from patients.age and
%    questionnaire_data. gradingOrchestrator.js then stores the result --
%    a migration adding to grading_results:
%
%      urgency_score      INTEGER CHECK (urgency_score BETWEEN 1 AND 100)
%      urgency_factor     TEXT
%      urgency_inputs     JSONB   -- exactly what went in, including whether
%                                    each value was measured or assumed
%
%    urgency_inputs is not optional bookkeeping. Without it, a score cannot be
%    explained or reproduced six months later, and the difference between a
%    lab HbA1c and a bucket midpoint disappears.
%
% 5. WHERE IT IS ALLOWED TO APPEAR. The ophthalmologist queue can sort by it
%    -- that is the point. It must NOT enter:
%      - the referral decision (that is the reviewer's, on the eye)
%      - the conformal tier (that is calibrated on the model's own error)
%      - the patient SMS
%    A synthetic-data score deciding who gets told to seek care would be
%    exactly the failure this file's header warns about.
%
% 6. THE API. Add to GET /api/v1/cases/:caseId:
%
%      "urgencyScore": 72,
%      "urgencyTopFactor": "HbA1c",
%      "urgencyBasis": "synthetic-model",     <- never omit this
%      "urgencyLimitation": "Trained on synthetic data ..."
%
%    null when the clinical inputs were missing. Null means "not computed",
%    and a missing HbA1c must never become a score of 1.
