'use strict';

/**
 * ids.js
 *
 * Locally-generated ID format, in one place.
 *
 * api-contracts.md, "Global ID rule": IDs generated by the PHC app (patients,
 * captures) look like
 *
 *     {PHC_CODE}-{base36 timestamp}-{4 random alphanumeric}
 *     e.g.  PHC001-lz3k9f-a2x9
 *
 * and are ALWAYS strings, never numbers, even where a database might use an
 * integer underneath.
 *
 * This lives in its own module because both captureHandler.js (Task 3.1) and
 * routes/patients.js (Task 3.2) mint IDs. Two copies of a format string is
 * exactly how the two drift apart, and a patient ID that does not match the
 * expected shape fails centrally, long after the PHC has gone offline.
 *
 * Why this shape:
 *   - The PHC prefix makes IDs globally unique without any coordination, which
 *     matters because PHCs generate IDs while offline and cannot ask a central
 *     server for one.
 *   - The base36 timestamp keeps IDs roughly sortable by creation time.
 *   - The random suffix breaks ties between two captures in the same
 *     millisecond -- a real possibility for scripted/batch imports.
 */

const crypto = require('crypto');

// Which PHC this install belongs to. Set PHC_CODE per deployment; the default
// only suits a single-site demo, and two sites both running the default would
// mint colliding IDs.
const PHC_CODE = process.env.PHC_CODE || 'PHC001';

const ALPHABET = 'abcdefghijklmnopqrstuvwxyz0123456789';

/**
 * randomSuffix(n)
 *
 * n random lowercase-alphanumeric characters.
 *
 * Uses crypto.randomBytes rather than Math.random, and rejects bytes in the
 * final incomplete block of the 256-value range instead of taking a plain
 * modulo -- a modulo would bias toward the first few letters of the alphabet.
 * The bias would not be a security problem here, but it would measurably raise
 * the collision rate, which is the one thing this suffix exists to prevent.
 */
function randomSuffix(n = 4) {
  const limit = Math.floor(256 / ALPHABET.length) * ALPHABET.length;
  let out = '';
  while (out.length < n) {
    for (const byte of crypto.randomBytes(n * 2)) {
      if (byte >= limit) continue;
      out += ALPHABET[byte % ALPHABET.length];
      if (out.length === n) break;
    }
  }
  return out;
}

/**
 * generateLocalId([phcCode])
 *
 * @param {string} [phcCode] — override the configured PHC code.
 * @returns {string} e.g. 'PHC001-lz3k9f-a2x9'
 */
function generateLocalId(phcCode = PHC_CODE) {
  return `${phcCode}-${Date.now().toString(36)}-${randomSuffix(4)}`;
}

module.exports = { generateLocalId, PHC_CODE };
